package org.fundacionjala.sfdc.pageobjects.Campaigns;

/**
 * CampaignInputs.
 */
public enum CampaignInputs {
    CAMPAIGN_NAME,
    CAMPAIGN_ACTIVE,
    CAMPAIGN_TYPE,
    CAMPAIGN_STATUS,
    CAMPAIGN_START_DATE,
    CAMPAIGN_END_DATE,
    CAMPAIGN_EXPECTED_REVENUE,
    CAMPAIGN_BUDGETED_COST,
    CAMPAIGN_ACTUAL_COST,
    CAMPAIGN_EXPECTED_RESPONSE,
    CAMPAIGN_NUM_SENT,
    CAMPAIGN_PARENT,
    CAMPAIGN_DESCRIPTION
}
