package org.fundacionjala.sfdc.pageobjects.contacts;

/**
 * ContactInputs.
 */
public enum ContactInputs {
    CONTACT_NAME,
    CONTACT_LAST_NAME,
    CONTACT_TITLE,
    CONTACT_DEPARTMENT,
    CONTACT_BIRTHDAY,
    CONTACT_PHONE,
    CONTACT_HOME_PHONE,
    CONTACT_MOBILE,
    CONTACT_OTHER_PHONE,
    CONTACT_FAX,
    CONTACT_EMAIL,
    CONTACT_ASSISTANT,
    CONTACT_ASST_PHONE,
    CONTACT_MAILING_STREET,
    CONTACT_OTHER_STREET,
    CONTACT_MAILING_CITY,
    CONTACT_OTHER_CITY,
    CONTACT_MAILING_STATE,
    CONTACT_OTHER_STATE,
    CONTACT_MAILING_ZIP,
    CONTACT_OTHER_ZIP,
    CONTACT_MAILING_COUNTRY,
    CONTACT_OTHER_COUNTRY,
    CONTACT_LANGUAGES,
    CONTACT_DESCRIPTION
}
