package org.fundacionjala.sfdc.pageobjects.opportunities;

/**
 * OpportInputs.
 */
public enum OpportInputs {
    OPPORTUNITY_PRIVATE,
    OPPORTUNITY_NAME,
    OPPORTUNITY_ACCOUNT_NAME,
    OPPORTUNITY_TYPE,
    OPPORTUNITY_LEAD_SOURCE,
    OPPORTUNITY_AMOUNT,
    OPPORTUNITY_CLOSE_DATE,
    OPPORTUNITY_NEXT_STEP,
    OPPORTUNITY_STAGE,
    OPPORTUNITY_PROBABILITY,
    OPPORTUNITY_PRIMARY_CAMPAIGN_SOURCE,
    OPPORTUNITY_ORDER_NUMBER,
    OPPORTUNITY_CURRENT_GENERATOR,
    OPPORTUNITY_TRACKING,
    OPPORTUNITY_MAIN_COMPETITORS,
    OPPORTUNITY_DELIVERY_INSTALLATION_STATUS,
    OPPORTUNITY_DESCRIPTION
}
