package org.fundacionjala.sfdc.util;

/**
 * Fields of Accunts and Contacs.
 */
public enum Inputs {
    ACCOUNT_NAME,
    PARENT_ACCOUNT,
    ACCOUNT_NUMBER,
    ACCOUNT_SITE,
    TYPE,
    INDUSTRY,
    ANUAL_REVENUE,
    CONTACT_NAME,
    CONTACT_LASTNAME,
    CONTACT_TITLE,
    CONTACT_DEPARTMENT,
    CONTACT_BIRTHDAY,
    CONTACT_LEADSOURCE,
    CONTACT_PHONE,
    CONTACT_HOMEPHONE,
    OPPORTUNITY_NAME,
    OPPORTUNITY_CLOSE_DATE,
    OPPORTUNITY_STAGE

}
