package org.fundacionjala.sfdc;

import org.fundacionjala.sfdc.pageobjects.Accounts.SFANewModifyPage;

import java.util.HashMap;
import java.util.Map;

/**
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'.
 */
public class Library {

    /**
     * Some library method.
     *
     * @return <code>true</code>
     */
    public boolean someLibraryMethod() {
        return true;
    }

}
