package org.fundacionjala.sfdc;

import org.fundacionjala.sfdc.pageobjects.Accounts.SFANewModifyPage;

import java.util.HashMap;
import java.util.Map;

/**
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'.
 */
public class Library {

    /**
     * Some library method.
     *
     * @return <code>true</code>
     */
    public boolean someLibraryMethod() {
        return true;
    }

    public static void getValues(Map<String, String> values, SFANewModifyPage newModifyPage) {
        Map<String, Value> valuesToFill = new HashMap<>();
        for (String value : values.keySet()) {
            valuesToFill.put(value, () -> {newModifyPage.setAccountNameTextField(values.get(value));});
        }

        valuesToFill.forEach((s, value) -> value.fillField());
    }
}
